/*
===============================================================================
Magnitude Analysis
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
SELECT 
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT 
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT
    p.category,
    COUNT(f.sales_amount) AS total_revenue
FROM gold.dim_products p
LEFT JOIN gold.fact_sales f
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- What is the total revenue generated by each customer?
    SELECT
        c.customer_key,
        c.first_name,
        c.last_name,
        SUM(f.sales_amount) AS total_revenue
    FROM gold.dim_customers c
    LEFT JOIN gold.fact_sales f 
    ON c.customer_key = f.customer_key
    GROUP BY c.customer_key,
             c.first_name,
             c.last_name
    ORDER BY total_revenue DESC;

 -- What is the distribution of sold items across countries?
 SELECT 
     c.country,
     COUNT(f.quantity) AS total_items_sold
 FROM gold.dim_customers c
 LEFT JOIN gold.fact_sales f
 ON c.customer_key = f.customer_key
 GROUP BY c.country
 ORDER BY total_items_sold DESC;


 /*
 ===============================================================================
 Ranking Analysis:
  - To rank data based on specific metrics and identify top performers.
     - For understanding the best and worst performers in the dataset.
     - Window Ranking Functions: RANK(), DENSE_RANK(), ROW_NUMBER()
     - GROUP BY, ORDER BY
 ===============================================================================
 */

 -- Which 5 products Generating the Highest Revenue?
 -- 1.simple mothod
SELECT TOP 5
   p.product_name,
   SUM(f.sales_amount) AS total_revenue
FROM gold.dim_products p
LEFT JOIN gold.fact_sales f
    ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;

-- 2. using window function & Subquery
SELECT *
FROM (
    SELECT
       p.product_name,
       SUM(f.sales_amount) AS total_revenue,
       RANK() OVER (ORDER BY SUM(f.sales_amount) DESC) AS rank_products
    FROM gold.dim_products p
    LEFT JOIN gold.fact_sales f
        ON p.product_key = f.product_key
    GROUP BY p.product_name
) t WHERE rank_products <= 5;

-- What are the 5 worst-performing products in terms of sales?
SELECT TOP 5
    p.product_name,
   SUM(f.sales_amount) AS total_revenue
FROM gold.dim_products p
LEFT JOIN gold.fact_sales f
    ON p.product_key = f.product_key
WHERE f.sales_amount IS NOT NULL
GROUP BY p.product_name
ORDER BY total_revenue;

-- Find the top 10 customers who have generated the highest revenue 
SELECT TOP 10
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales f
    ON c.customer_key = f.customer_key
GROUP BY c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- The 3 customers with the fewest orders placed
SELECT TOP 3
    c.customer_key,
    c.first_name,
    c.last_name,
COUNT(DISTINCT f.order_number) AS total_orders
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales f
ON c.customer_key = f.customer_key
GROUP BY c.customer_key,
         c.first_name,
         c.last_name
ORDER BY total_orders

/*
===============================================================================
Change Over Time Analysis:
    - To track trends, growth, and changes in key metrics over time.
    - For time-series analysis and identifying seasonality.
    - To measure growth or decline over specific periods.
    - Date Functions: DATEPART(), DATETRUNC(), FORMAT()
    - Aggregate Functions: SUM(), COUNT(), AVG()
===============================================================================
*/

-- Analyse sales performance over time
-- Quick Date Functions
SELECT
    YEAR(order_date) order_year,
    MONTH(order_date) order_month,
    SUM(sales_amount) total_sales,
    COUNT(DISTINCT customer_key) total_customers
FROM gold.fact_sales 
WHERE order_date IS NOT NULL
GROUP BY YEAR(order_date), MONTH(order_date)
ORDER BY YEAR(order_date), MONTH(order_date) 

-- Using DATETRUNC()
SELECT
    DATETRUNC(month,order_date) order_date, --DATETRUNC(year,order_date) order_date
    SUM(sales_amount) total_sales,
    COUNT(DISTINCT customer_key) total_customers
FROM gold.fact_sales 
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(month,order_date)
ORDER BY DATETRUNC(month,order_date)

/*
===============================================================================
Cumulative Analysis:
    - To calculate running totals or moving averages for key metrics.
    - To track performance over time cumulatively.
    - Useful for growth analysis or identifying long-term trends.
    - Window Functions: SUM() OVER(), AVG() OVER()
===============================================================================
*/

-- Calculate the total sales per month 
-- and the running total of sales over time 

SELECT
    order_date,
    total_sales,
    SUM(total_sales) OVER (ORDER BY order_date) AS runnig_total_sales,
    AVG(avg_price) OVER (ORDER BY order_date) AS moving_avrg_sales
FROM(
    SELECT
        DATETRUNC(month,order_date) order_date, 
        SUM(sales_amount) total_sales,
        AVG(price) avg_price
    FROM gold.fact_sales 
    WHERE order_date IS NOT NULL
    GROUP BY DATETRUNC(month,order_date) 
    )t 

